### ISSUE TITLE
gambly.txt blocks too much :/

### ISSUE THREAD

**Issue by prologic** [alexsannikov/adguardhome-filters#1]
I'm using (*or I was*) quite a few of your filter rules remotely via Github raw URIs.

Your recent changes to [gambling.txt](https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/extensions/gambling/gambling.txt) however contains a rule like this:

```
||io
```

This blocks far too much of the useful Internet -- including (*funnily enough*) my own domain name internally and externally :/

Where/How are you generating these rules? I've had to disable all the rules I use from your repo  as they break the whole Internet for me :)

**Comment by prologic** [comment]
Btw the issue isn't just that `||io` was blocking `*.io` domains -- But that everything broke; AdGuardDNS now started blocking 100% of DNS requests -- broken rule somewhere? I'll need to check the logs a bit more later...

The reason I also bring up the breakage of `*.io` domains is when trying to figure out wtf happened; my own tooling was also not working becuase that rule blocked all my infra :)

**Comment by alexsannikov** [comment]
That looks like to be some temporary problem with filters as I've been playing with filtering and optimization algorithms. Now I cannot find any "||io" line in any filter file.
Tried to reduce number of lines and delete all the extra-entries, if parent domain is blocked already.

**Comment by alexsannikov** [comment]
Forgot to mention: 
1. You can use _allowing_ rule for your domain (or any other) to beat any disable rule. It will work even if it is still presented. For AdGuard home just click "Allow" on the blocked line in the log;
2. I just download files from Steve Black source (link is under this project description), and then preform some cleanup. Steve's files are _hosts_ files, so they have multiple overlapping lines. For AdGuard Home, it is excessive, as AGH may use some "intellectual" filtering and not requires each domain name to be presented.
3. I changed the scripts logic last weekend, and hope now everything started to be more stable and compact.
Thanks.

**Comment by prologic** [comment]
Thanks for the update and explanation! I'll re-enable the use of thse rules soon and see how it goes. THey do block a lot more useless traffic so I like them :)

**Comment by alexsannikov** [comment]
You're welcome.
