### ISSUE TITLE
Instagram being blocked by porn.txt on last update

### ISSUE THREAD

**Issue by VCTGomes** [alexsannikov/adguardhome-filters#11]
Hi, unfortunately the Instagram has been added porn.txt list and it's blocking my Instagram access. I think it's a mistake, because Instagram shouldn't be considered as an adult website.

I hope you guys could remove it. Thanks.

**Comment by alexsannikov** [comment]
Hello,

These filter files are generated automatically based on StevenBlack repo (https://github.com/StevenBlack/hosts). Any mistakes in filtering might be reported to the original source creator (Steven), and all the changes made there will be reflected in further updates.
Also, personal allowing filters may override any incorrect disabling filters to get access to the resources immediately.
