### ISSUE TITLE
add rule34.us

### ISSUE THREAD

**Issue by verygenericname** [alexsannikov/adguardhome-filters#12]
not blocked

**Comment by alexsannikov** [comment]
Hello,

These filter files are generated automatically based on StevenBlack repo (https://github.com/StevenBlack/hosts). Any mistakes in filtering might be reported to the original source creator (Steven), and all the changes made there will be reflected in further updates.
Also, personal allowing filters may override any incorrect disabling filters to get access to the resources immediately.
