### ISSUE TITLE
www.dday.it blocked by porn filter

### ISSUE THREAD

**Issue by dpeddi** [alexsannikov/adguardhome-filters#13]
Hello,

Rule(s)
||b-cdn.net^
Adult Websites

Original response
CNAME: opiquad.b-cdn.net. (ttl=2949)
A: 84.17.59.115 (ttl=14)

Please check

**Comment by alexsannikov** [comment]
Hello,

These filter files are generated automatically based on StevenBlack repo (https://github.com/StevenBlack/hosts). Any mistakes in filtering might be reported to the original source creator (Steven), and all the changes made there will be reflected in further updates.
Also, personal allowing filters may override any incorrect disabling filters to get access to the resources immediately.
