### ISSUE TITLE
False Positive: e926.net (Porn Filter)

### ISSUE THREAD

**Issue by Eaterminer** [alexsannikov/adguardhome-filters#14]
e926.net is a SFW mirror of e621.net, while despite sharing the same R18 warning is filled with SFW content.

**Comment by alexsannikov** [comment]
Hello,

These filter files are generated automatically based on StevenBlack repo (https://github.com/StevenBlack/hosts). Any mistakes in filtering might be reported to the original source creator (Steven), and all the changes made there will be reflected in further updates.
Also, personal allowing filters may override any incorrect disabling filters to get access to the resources immediately.
