### ISSUE TITLE
"||www.be" in malware list ?

### ISSUE THREAD

**Issue by YBS-PC** [alexsannikov/adguardhome-filters#2]
"||www.be" in malware list ?

**Comment by alexsannikov** [comment]
Yes. Based on Steven's hosts list it is there:
0.0.0.0 www.be

**Comment by alexsannikov** [comment]
Also, based on the same admalware.txt file, two other domains from same level TLD in the blacklist:
./admalware.txt:||www.fr
./admalware.txt:||www.mu
