### ISSUE TITLE
Raspberrypi Blocked

### ISSUE THREAD

**Issue by x-o-r-r-o** [alexsannikov/adguardhome-filters#3]
Your admalware block list blocks raspberrypi.org all requests including subdomains. check and remove raspberrypi.org is not a malware domain. Raspbian Buster is unable to update anymore due to this block.

Now i assume your list must have blocked many other legit domains so i have decided not to use until you review valid domains and fix this issue.

**Comment by alexsannikov** [comment]
All the filter lists are taken from free sources. I have no idea why this domain name was included into blacklist by the original authors.
However, raspberrypi.org is the legitimate domain, so I manually cleared this record for convenience.
Done.
