### ISSUE TITLE
Could not import into AdGuardHome

### ISSUE THREAD

**Issue by diepnt90** [alexsannikov/adguardhome-filters#4]
Hi,

I could not import into Adguard home as it threw an error as the image
![Screenshot 2021-10-10 094257](https://user-images.githubusercontent.com/18731180/136679507-e97a1ba1-ab7d-45b1-ab98-4b1ecc1c1cbb.png)

**Comment by mgdz** [comment]
try this link https://raw.githubusercontent.com/alexsannikov/adguardhome-filters/master/porn.txt

**Comment by alexsannikov** [comment]
You should use plain text (RAW) file link instead of HTML. The link above is correct. All other files may be linked using same path but different filenames.
