### ISSUE TITLE
remove yastatic.net from rueasylist

### ISSUE THREAD

**Issue by POMATu** [alexsannikov/adguardhome-filters#5]
without yastatic no yandex services are working
neither maps nor market.yandex.ru
this is irrelevant filter you supposed to block trackers and ads but not break your internet usability

after adding whitelist
`@@||yastatic.net^$important`
yandex sites work again
even tho I have ad block plus addon with exact same Rueasylist + Easylist filter

why do you even try to block CDN static domains with too broad appliance?

**Comment by alexsannikov** [comment]
RuEasyList is pulled from schakal.ru site and prepared for use in AdGuardHome. If you think some domains must be excluded from original filter list, please contact author over 4PDA forum "https://4pda.to/forum/index.php?showtopic=275091&st=8020#entry89665467"
