### ISSUE TITLE
Remove zoom.us

### ISSUE THREAD

**Issue by scamp** [alexsannikov/adguardhome-filters#6]
Please remove zoom.us from RU EasyList.
This kind of blocking is too broad, and breaks completely well-known video conferencing service.

Adding the following line to user-defined filters in AdGuard helps as workaround:

@@||zoom.us^$important

**Comment by alexsannikov** [comment]
Done.
Domain zoom.us removed from "admalware" and "rueasylist".
Workaround works too :)
