### ISSUE TITLE
remove feeds.ausha.co

### ISSUE THREAD

**Issue by erdoukki** [alexsannikov/adguardhome-filters#7]
![Capture d’écran du 2022-06-30 10-15-44](https://user-images.githubusercontent.com/2179472/176628053-ce1085a6-f094-4bf7-b4fb-cd8294b90dc2.png)

feeds.ausha.co are podcasts !
```
Détails de la réponse
État
Bloqué par CNAME ou adresse IP
Serveur DNS
8.8.8.8:53
Écoulé
62 ms
Code de réponse
NOERROR
Règle(s)

    ||b-cdn.net^
Adult Porn List

Réponse
AAAA: :: (ttl=10)
Réponse originale
CNAME: aushafeeds.b-cdn.net. (ttl=120) 
```

https://feed.ausha.co/AjV53skmDzO3

**Comment by alexsannikov** [comment]
Hello,
AdGuardHome filter list is completely under AdGuardHome team management, so I cannot change it as I just pull it every time from the original source.
However, you can always "enable" locked records with @@ directive. Please read AdGuardHome Wiki page.
Example:
- disable rule: ||blogspot.com
- to overwrite this rule and enable it: @@||blogspot.com^$important

**Comment by erdoukki** [comment]
> to overwrite this rule and enable it: @@||blogspot.com^$important

Thx
