### ISSUE TITLE
image.tmdb.org considered as porn ?

### ISSUE THREAD

**Issue by ejalal** [alexsannikov/adguardhome-filters#9]
Hey all,

I had issues with my Jellyfin instance not displaying movie posters and other actor images for months, and just figured out that it's being blocked by the porn filter as part of the ||b-cdn.net rule !!

![image](https://user-images.githubusercontent.com/19426471/219667850-a28dcaa9-2591-48f2-a561-bf836ee5c3ba.png)

I added an exception for image.tmdb.org but it could be removed from the list at source.

**Comment by alexsannikov** [comment]
Hello,
b-cdn.net is indeed in the porn filter's file as per StevenBlack repo (domain www.b-cdn.net, actually).
As usually 3rd level domain "www" logically is same as 2nd level domain, I assume "www.[fqdn].[tld]" is same as "[fqdn].[tld]".
If domain of 2nd level is in block list, all sub-domains (including www and any others) are blocked by AdGuard, following this logic.
Regarding "image.tmdb.com" - I couldn't find this domain name in any of blocklist, and suppose it's redirected to b-cdn.net somehow, and then blocked.
If you need this domain to be available, you can make exception, and you already did it.
As all the filter lists are prepared by the automated scripts from different sources, combined, cleaned up, and pushed into GitHub repo, it means that you need to request original list's owner to exclude some domains from original list. Thus, they will disappear in this repository/files too.
